// (login) 设置用户信息
export const SET_USERINFO = 'SET_USERINFO';
// login请求状态中
export const SET_LOGINFLAG = 'SET_LOGINFLAG';

// (orderQuery) 设置页数
export const SET_ORDERQUERY_PAGENUMBER = 'SET_ORDERQUERY_PAGENUMBER';
// 设置订单列表
export const SET_ORDERQUERY_ORDERLIST = 'SET_ORDERQUERY_ORDERLIST';
// 设置总页数
export const SET_ORDERQUERY_TOTAL = 'SET_ORDERQUERY_TOTAL';
// 设置选择查询的条件
export const SET_ORDERQUERY_RADIOVALUE = 'SET_ORDERQUERY_RADIOVALUE';
// 设置查询的内容
export const SET_ORDERQUERY_INPUTVALUE = 'SET_ORDERQUERY_INPUTVALUE';

// (dataMachine) 设置机列表
export const SET_DATAMACHINE_MACHINELIST = 'SET_DATAMACHINE_MACHINELIST';
// 时间值
export const SET_DATAMACHINE_TIMEVALUE = 'SET_DATAMACHINE_TIMEVALUE';
